import { GigReview } from '../types';

export const INITIAL_GIG_REVIEWS: GigReview[] = [
  {
    id: 'rev_101',
    order_id: 'ord_sample_901',
    order_number: 'NAIN-ORD-62184',
    gig_id: 'gig_mix_01',
    seller_id: 'usr_nain_9281',
    buyer_id: 'usr_sarah_j',
    buyer_name: 'Sarah Jenkins',
    buyer_username: 'sarahjenkins_music',
    buyer_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    buyer_location: 'London, UK',
    rating: 5,
    sub_ratings: {
      communication: 5,
      service_as_described: 5,
      quality_of_delivery: 5,
    },
    review_text: 'Absolutely blown away by the clarity and stereo image! Delivered 24 hours ahead of schedule. The analog bus warmth and precision vocal pocketing completely elevated our indie pop single. Reached -9 LUFS with zero pumping or distortion. Nain understood the creative brief instantly.',
    package_name: 'Gold Pro Mix & Master',
    package_type: 'standard',
    price_inr: 5499,
    created_at: new Date(Date.now() - 3600000 * 24 * 3).toISOString(), // 3 days ago
    helpful_count: 14,
    verified_purchase: true,
    tags: ['Analog Warmth', 'Radio Ready', 'Fast Turnaround'],
    seller_response: {
      message: 'Thank you Sarah! Loved working with your dynamic vocal arrangements and acoustic textures. Looking forward to your next release!',
      responded_at: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
    },
  },
  {
    id: 'rev_102',
    order_id: 'ord_sample_902',
    order_number: 'NAIN-ORD-51920',
    gig_id: 'gig_mix_01',
    seller_id: 'usr_nain_9281',
    buyer_id: 'usr_rohan_v',
    buyer_name: 'Rohan Verma',
    buyer_username: 'rohanbeats',
    buyer_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    buyer_location: 'Mumbai, India',
    rating: 5,
    sub_ratings: {
      communication: 5,
      service_as_described: 5,
      quality_of_delivery: 5,
    },
    review_text: 'The best audio engineer on Nain Music without question. He separated our 808 sub and kick drum so cleanly that the track now hits hard on club systems and phone speakers alike. Pristine 24-bit 48kHz WAV master delivery.',
    package_name: 'Platinum Commercial Master',
    package_type: 'premium',
    price_inr: 9999,
    created_at: new Date(Date.now() - 3600000 * 24 * 7).toISOString(), // 7 days ago
    helpful_count: 9,
    verified_purchase: true,
    tags: ['Deep Bass Clarity', 'Pristine 24-bit WAV', 'Punchy Drums'],
  },
  {
    id: 'rev_103',
    order_id: 'ord_sample_903',
    order_number: 'NAIN-ORD-43187',
    gig_id: 'gig_mix_01',
    seller_id: 'usr_nain_9281',
    buyer_id: 'usr_arjun_k',
    buyer_name: 'Arjun Kapoor',
    buyer_username: 'arjun_recordings',
    buyer_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    buyer_location: 'Bangalore, India',
    rating: 5,
    sub_ratings: {
      communication: 5,
      service_as_described: 5,
      quality_of_delivery: 5,
    },
    review_text: 'Vocal pitch correction with Melodyne was so natural and transparent that nobody could tell it was tuned. The bridge reverb automation gave me goosebumps. Outstanding communication throughout.',
    package_name: 'Silver Stem Mix',
    package_type: 'basic',
    price_inr: 2499,
    created_at: new Date(Date.now() - 3600000 * 24 * 12).toISOString(),
    helpful_count: 6,
    verified_purchase: true,
    tags: ['Natural Vocal Tuning', 'Great Communication'],
    seller_response: {
      message: 'Much appreciated Arjun! Melodyne surgical tuning on soulful vocals is always a pleasure to work with.',
      responded_at: new Date(Date.now() - 3600000 * 24 * 11).toISOString(),
    },
  },
  {
    id: 'rev_104',
    order_id: 'ord_sample_904',
    order_number: 'NAIN-ORD-38812',
    gig_id: 'gig_mix_01',
    seller_id: 'usr_nain_9281',
    buyer_id: 'usr_elena_r',
    buyer_name: 'Elena Rostova',
    buyer_username: 'elena_soundlab',
    buyer_avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    buyer_location: 'Berlin, Germany',
    rating: 5,
    sub_ratings: {
      communication: 4,
      service_as_described: 5,
      quality_of_delivery: 5,
    },
    review_text: 'Very professional mixing setup. Handled our 40-track multitrack with patience and applied all timestamped notes quickly during the revision round. The final Apple Digital Masters standard is top notch.',
    package_name: 'Platinum Commercial Master',
    package_type: 'premium',
    price_inr: 9999,
    created_at: new Date(Date.now() - 3600000 * 24 * 18).toISOString(),
    helpful_count: 4,
    verified_purchase: true,
    tags: ['Apple Digital Masters', 'Pro Revisions'],
  },
  {
    id: 'rev_105',
    order_id: 'ord_sample_905',
    order_number: 'NAIN-ORD-29004',
    gig_id: 'gig_mix_01',
    seller_id: 'usr_nain_9281',
    buyer_id: 'usr_kabir_s',
    buyer_name: 'Kabir Sen',
    buyer_username: 'kabir_sen_music',
    buyer_avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    buyer_location: 'Kolkata, India',
    rating: 5,
    sub_ratings: {
      communication: 5,
      service_as_described: 5,
      quality_of_delivery: 5,
    },
    review_text: 'Tested the master across multiple environments: AirPods, car audio, and studio monitors. Translation is incredible, vocal cuts through cleanly over dense guitars. Will be sending my entire EP here.',
    package_name: 'Gold Pro Mix & Master',
    package_type: 'standard',
    price_inr: 5499,
    created_at: new Date(Date.now() - 3600000 * 24 * 25).toISOString(),
    helpful_count: 8,
    verified_purchase: true,
    tags: ['Superb Translation', 'AirPods & Car Tested'],
  }
];
